sudo: required
language: node_js
node_js:
- 9
services:
- postgresql
- docker

env:
  global:
  - DATABASE_HOST=localhost
  - APP_PORT=80
  - APP_LOG_DIR=`pwd`/log
  - DOCKER_IMAGE_NAME=$TRAVIS_REPO_SLUG:$TRAVIS_COMMIT
before_install:
- psql -f ./db/container-files/docker-entrypoint-initdb.d/db.sql -U postgres
- cd ./app
install:
- npm install -s
- npm run -s build
before_script:
- mkdir -p $APP_LOG_DIR
script:
- npm run -s lint
- ./bin/run-tests-coverage && npm run -s coveralls-coverage
- npm run -s test-coverage-report && npm run -s test-coverage-check
- cd $TRAVIS_BUILD_DIR && docker build -t $DOCKER_IMAGE_NAME . && echo "built $DOCKER_IMAGE_NAME"