db:
  image: ihsw/es-bueno-db

base:
  image: ihsw/es-bueno
  environment:
    - DATABASE_HOST=Db
test-base:
  extends:
    service: base
  command: ./bin/run-tests

test:
  extends:
    service: test-base
  links:
    - db:Db
test-dev:
  extends:
    service: test-base
  links:
    - db:Db
  volumes:
    - ./app:/srv/app

web:
  extends:
    service: base
  links:
    - db:Db
  ports:
    - 80:80
