db:
  image: ihsw/es-bueno-db

base:
  image: ihsw/es-bueno
test-base:
  extends:
    service: base
  command: ./bin/run-tests

test:
  extends:
    service: test-base
  links:
  - db:Db
  environment:
  - DATABASE_HOST=Db

test-dev:
  extends:
    service: test-base
  environment:
  - DATABASE_HOST=Db
  links:
  - db:Db
  volumes:
  - ./app:/home/es-bueno/app

web:
  extends:
    service: base
  environment:
  - DATABASE_HOST=Db
  links:
  - db:Db
  ports:
  - 80:80
