db:
  image: ihsw/es-bueno-db

base:
  image: ihsw/es-bueno
test-base:
  extends:
    service: base
  command: npm test

test:
  extends:
    service: test-base
  links:
    - db
test-dev:
  extends:
    service: test-base
  volumes:
    - ./app:/srv/app
  links:
    - db
