db:
  image: ihsw/es-bueno-db

base:
  image: ihsw/es-bueno
  environment:
    - ENV=local
test-base:
  extends:
    service: base
  command: ./bin/run-tests

web-dev:
  extends:
    service: base
  volumes:
    - ./app:/srv/app
  links:
    - db

web-test:
  extends:
    service: base
  links:
    - db

test:
  extends:
    service: test-base
  links:
    - db
test-dev:
  extends:
    service: test-base
  volumes:
    - ./app:/srv/app
  links:
    - db
