db:
  image: ihsw/es-bueno-db

base:
  image: ihsw/es-bueno
  environment:
    - DATABASE_HOST=Db
    - REQUEST_LOGGING=1
test-base:
  extends:
    service: base
  command: ./bin/run-tests

test:
  extends:
    service: test-base
  links:
    - db:Db
test-dev:
  extends:
    service: test-base
  links:
    - db:Db
  # external_links:
    # - elk-server:log-egress
  volumes:
    - ./app:/home/es-bueno/app

web:
  extends:
    service: base
  links:
    - db:Db
  ports:
    - 80:8080
